import type { DocItem, Equipment, Source } from "./types";

export interface ManufacturerSourceRecord {
  id: string;
  manufacturer: string;
  equipmentTypes: string[];
  title: string;
  model: string;
  category: DocItem["category"];
  url: string;
  reviewedAt: string;
  aiIndexSummary: string;
  verificationNote: string;
}

export const MANUFACTURER_SOURCE_REVIEWED_AT = "2026-06-29";

export const MANUFACTURER_SOURCE_LIBRARY: ManufacturerSourceRecord[] = [
  {
    id: "mfg-goodman-ac",
    manufacturer: "Goodman",
    equipmentTypes: ["Air Conditioner"],
    title: "Goodman air conditioners product library",
    model: "Current Goodman AC families",
    category: "spec_sheet",
    url: "https://www.goodmanmfg.com/products/air-conditioners",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Goodman product library for current residential air conditioner families. Use it to locate the exact family page or submittal before extracting numeric values.",
    verificationNote: "Exact MCA, MOP, charge, dimensions, wiring, and parts must be confirmed against the installed model nameplate and model-specific literature.",
  },
  {
    id: "mfg-goodman-heat-pumps",
    manufacturer: "Goodman",
    equipmentTypes: ["Heat Pump"],
    title: "Goodman heat pumps product library",
    model: "Current Goodman heat-pump families",
    category: "spec_sheet",
    url: "https://www.goodmanmfg.com/products/heat-pumps",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Goodman heat-pump library for current residential split-system families.",
    verificationNote: "Use it to locate the exact model family PDF, then confirm all service values against the installed nameplate before relying on them.",
  },
  {
    id: "mfg-goodman-gas-furnaces",
    manufacturer: "Goodman",
    equipmentTypes: ["Gas Furnace"],
    title: "Goodman gas furnaces product library",
    model: "Current Goodman gas furnace families",
    category: "spec_sheet",
    url: "https://www.goodmanmfg.com/products/gas-furnaces",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Goodman furnace library covering current 80 and 90+ AFUE residential families.",
    verificationNote: "Use the family page only as a pointer until the exact cabinet, input size, and revision are confirmed from model literature.",
  },
  {
    id: "mfg-goodman-air-handlers-coils",
    manufacturer: "Goodman",
    equipmentTypes: ["Air Handler", "Evaporator Coil"],
    title: "Goodman air handlers and coils product library",
    model: "Current Goodman indoor-unit families",
    category: "spec_sheet",
    url: "https://www.goodmanmfg.com/products/air-handlers-and-coils",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Goodman indoor-unit library for air handlers and evaporator coils.",
    verificationNote: "Matched-system data still requires the exact indoor model and approved pairing literature.",
  },
  {
    id: "mfg-amana-ac",
    manufacturer: "Amana",
    equipmentTypes: ["Air Conditioner"],
    title: "Amana air conditioners product library",
    model: "Current Amana AC families",
    category: "spec_sheet",
    url: "https://www.amana-hac.com/products/air-conditioners",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Amana product library for current residential air conditioner families.",
    verificationNote: "Use as a source pointer only until exact model literature is reviewed.",
  },
  {
    id: "mfg-carrier-ac",
    manufacturer: "Carrier",
    equipmentTypes: ["Air Conditioner", "Package Gas/Electric", "Package Heat Pump", "RTU"],
    title: "Carrier residential air conditioners product library",
    model: "Current Carrier cooling families",
    category: "spec_sheet",
    url: "https://www.carrier.com/us/en/residential/air-conditioners/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier residential air conditioner library. Use it to select the exact model family and then review product data before quoting specs.",
    verificationNote: "Do not use family marketing pages as numeric service specifications.",
  },
  {
    id: "mfg-carrier-heat-pumps",
    manufacturer: "Carrier",
    equipmentTypes: ["Heat Pump"],
    title: "Carrier residential heat pumps product library",
    model: "Current Carrier heat-pump families",
    category: "spec_sheet",
    url: "https://www.carrier.com/us/en/residential/heat-pumps/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier residential heat-pump library for current families.",
    verificationNote: "Use as a source pointer only until model-specific product data or installation literature is reviewed.",
  },
  {
    id: "mfg-carrier-furnaces",
    manufacturer: "Carrier",
    equipmentTypes: ["Gas Furnace"],
    title: "Carrier residential furnaces product library",
    model: "Current Carrier gas furnace families",
    category: "spec_sheet",
    url: "https://www.carrier.com/us/en/residential/furnaces/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier residential furnace library.",
    verificationNote: "Exact service procedures require the model-specific install or service document, not the category page alone.",
  },
  {
    id: "mfg-carrier-air-handlers",
    manufacturer: "Carrier",
    equipmentTypes: ["Air Handler", "Fan Coil / Air Handler"],
    title: "Carrier residential air handlers product library",
    model: "Current Carrier fan-coil and air-handler families",
    category: "spec_sheet",
    url: "https://www.carrier.com/us/en/residential/air-handlers/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier air-handler and fan-coil family library.",
    verificationNote: "Use to locate the exact FV/CV family page or PDF before extracting electrical or airflow values.",
  },
  {
    id: "mfg-carrier-evaporator-coils",
    manufacturer: "Carrier",
    equipmentTypes: ["Evaporator Coil"],
    title: "Carrier residential evaporator coils product library",
    model: "Current Carrier evaporator-coil families",
    category: "spec_sheet",
    url: "https://www.carrier.com/us/en/residential/evaporator-coils/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier residential evaporator-coil library.",
    verificationNote: "Coil selection still requires the exact coil model and matched AHRI combination review.",
  },
  {
    id: "mfg-carrier-ductless",
    manufacturer: "Carrier",
    equipmentTypes: ["Mini-Split Outdoor", "Mini-Split Indoor"],
    title: "Carrier ductless mini-splits product library",
    model: "Current Carrier ductless families",
    category: "service_manual",
    url: "https://www.carrier.com/us/en/residential/ductless-mini-splits/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier ductless product library.",
    verificationNote: "Indoor and outdoor model pairing must be confirmed before using ductless literature for service decisions.",
  },
  {
    id: "mfg-carrier-iaq",
    manufacturer: "Carrier",
    equipmentTypes: ["Thermostat", "Dehumidifier", "Humidifier", "Media Air Cleaner", "UV Accessory", "ERV/HRV", "Zoning Panel"],
    title: "Carrier indoor air quality and controls library",
    model: "Current Carrier IAQ and control families",
    category: "service_manual",
    url: "https://www.carrier.com/us/en/residential/indoor-air-quality/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Carrier residential IAQ and control entry for accessory-class equipment.",
    verificationNote: "Accessory wiring and configuration changes still require the exact accessory install guide before work begins.",
  },
  {
    id: "mfg-bryant-ac",
    manufacturer: "Bryant",
    equipmentTypes: ["Air Conditioner"],
    title: "Bryant air conditioners product library",
    model: "Current Bryant AC families",
    category: "spec_sheet",
    url: "https://www.bryant.com/en/us/products/air-conditioners/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bryant product library for current residential air conditioner families.",
    verificationNote: "Exact service values require the model-specific product data or nameplate.",
  },
  {
    id: "mfg-bryant-heat-pumps",
    manufacturer: "Bryant",
    equipmentTypes: ["Heat Pump"],
    title: "Bryant heat pumps product library",
    model: "Current Bryant heat-pump families",
    category: "spec_sheet",
    url: "https://www.bryant.com/en/us/products/heat-pumps/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bryant residential heat-pump library.",
    verificationNote: "Treat the library as a source pointer until exact model literature is reviewed.",
  },
  {
    id: "mfg-bryant-furnaces",
    manufacturer: "Bryant",
    equipmentTypes: ["Gas Furnace"],
    title: "Bryant gas furnaces product library",
    model: "Current Bryant gas furnace families",
    category: "spec_sheet",
    url: "https://www.bryant.com/en/us/products/gas-furnaces/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bryant residential furnace library.",
    verificationNote: "Use the category page only to locate exact literature; do not treat it as an approved service procedure source by itself.",
  },
  {
    id: "mfg-bryant-air-handlers",
    manufacturer: "Bryant",
    equipmentTypes: ["Air Handler", "Fan Coil / Air Handler"],
    title: "Bryant air handlers and fan coils product library",
    model: "Current Bryant indoor-unit families",
    category: "spec_sheet",
    url: "https://www.bryant.com/en/us/products/air-handlers/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bryant air-handler and fan-coil family library.",
    verificationNote: "Exact indoor-model and matched-system data still need model-specific literature review.",
  },
  {
    id: "mfg-trane-ac",
    manufacturer: "Trane",
    equipmentTypes: ["Air Conditioner", "Heat Pump"],
    title: "Trane residential air conditioners product library",
    model: "Current Trane cooling families",
    category: "spec_sheet",
    url: "https://www.trane.com/residential/en/products/air-conditioners/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Trane residential air conditioner library for current product families.",
    verificationNote: "Use as a source pointer until the exact installed model is reviewed.",
  },
  {
    id: "mfg-trane-furnaces",
    manufacturer: "Trane",
    equipmentTypes: ["Gas Furnace"],
    title: "Trane residential furnaces product library",
    model: "Current Trane furnace families",
    category: "spec_sheet",
    url: "https://www.trane.com/residential/en/products/furnaces/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Trane residential furnace library.",
    verificationNote: "Use this to locate exact S-series literature before relying on ignition, venting, or electrical details.",
  },
  {
    id: "mfg-trane-air-handlers",
    manufacturer: "Trane",
    equipmentTypes: ["Air Handler"],
    title: "Trane residential air handlers product library",
    model: "Current Trane air-handler families",
    category: "spec_sheet",
    url: "https://www.trane.com/residential/en/products/air-handlers/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Trane residential air-handler library.",
    verificationNote: "Exact TEM/TAM family literature is still required before extracting airflow or heat-kit values.",
  },
  {
    id: "mfg-trane-thermostats",
    manufacturer: "Trane",
    equipmentTypes: ["Thermostat"],
    title: "Trane thermostats product library",
    model: "Current Trane thermostat families",
    category: "service_manual",
    url: "https://www.trane.com/residential/en/products/thermostats/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Trane thermostat product library.",
    verificationNote: "Use it to identify the exact control, then open the matching install guide before changing wiring or setup.",
  },
  {
    id: "mfg-trane-rtu",
    manufacturer: "Trane",
    equipmentTypes: ["RTU", "Package Gas/Electric", "Package Heat Pump"],
    title: "Trane commercial rooftop units product library",
    model: "Current Trane packaged and rooftop families",
    category: "service_manual",
    url: "https://www.trane.com/commercial/north-america/us/en/products-systems/packaged-units-and-split-systems/rooftop-units.html",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Trane commercial rooftop-unit library.",
    verificationNote: "Exact Voyager, Precedent, or other rooftop literature is still required before using this as a repair source.",
  },
  {
    id: "mfg-american-standard-ac",
    manufacturer: "American Standard",
    equipmentTypes: ["Air Conditioner", "Heat Pump"],
    title: "American Standard air conditioners product library",
    model: "Current American Standard cooling families",
    category: "spec_sheet",
    url: "https://www.americanstandardair.com/products/air-conditioners/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official American Standard air conditioner product library.",
    verificationNote: "Exact values require model-specific literature and nameplate confirmation.",
  },
  {
    id: "mfg-american-standard-furnaces",
    manufacturer: "American Standard",
    equipmentTypes: ["Gas Furnace"],
    title: "American Standard furnaces product library",
    model: "Current American Standard furnace families",
    category: "spec_sheet",
    url: "https://www.americanstandardair.com/products/furnaces/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official American Standard residential furnace library.",
    verificationNote: "Use only as a pointer until exact model literature and nameplate values are reviewed.",
  },
  {
    id: "mfg-lennox-ac",
    manufacturer: "Lennox",
    equipmentTypes: ["Air Conditioner", "Heat Pump", "RTU"],
    title: "Lennox air conditioners product library",
    model: "Current Lennox cooling families",
    category: "spec_sheet",
    url: "https://www.lennox.com/residential/products/heating-cooling/air-conditioners",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Lennox air conditioner product library.",
    verificationNote: "Do not extract numeric service specs until the exact model document is approved.",
  },
  {
    id: "mfg-lennox-heat-pumps",
    manufacturer: "Lennox",
    equipmentTypes: ["Heat Pump"],
    title: "Lennox heat pumps product library",
    model: "Current Lennox heat-pump families",
    category: "spec_sheet",
    url: "https://www.lennox.com/residential/products/heating-cooling/heat-pumps",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Lennox residential heat-pump library.",
    verificationNote: "Use as a source pointer until exact ML/EL/SL family literature is approved.",
  },
  {
    id: "mfg-lennox-furnaces",
    manufacturer: "Lennox",
    equipmentTypes: ["Gas Furnace"],
    title: "Lennox furnaces product library",
    model: "Current Lennox furnace families",
    category: "spec_sheet",
    url: "https://www.lennox.com/residential/products/heating-cooling/furnaces",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Lennox residential furnace library.",
    verificationNote: "Exact installation or service values require the precise model family document.",
  },
  {
    id: "mfg-lennox-air-handlers",
    manufacturer: "Lennox",
    equipmentTypes: ["Air Handler"],
    title: "Lennox air handlers product library",
    model: "Current Lennox air-handler families",
    category: "spec_sheet",
    url: "https://www.lennox.com/residential/products/heating-cooling/air-handlers",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Lennox residential air-handler library.",
    verificationNote: "Use the product library to find exact indoor-unit documentation before using electrical or airflow data.",
  },
  {
    id: "mfg-lennox-controls",
    manufacturer: "Lennox",
    equipmentTypes: ["Thermostat", "Dehumidifier", "Humidifier", "Media Air Cleaner", "UV Accessory", "ERV/HRV", "Zoning Panel"],
    title: "Lennox comfort controls and indoor air quality library",
    model: "Current Lennox controls and IAQ families",
    category: "service_manual",
    url: "https://www.lennox.com/residential/products/indoor-air-quality",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Lennox controls and IAQ entry for thermostat and accessory-class equipment.",
    verificationNote: "Open the exact control or IAQ accessory document before changing configuration or wiring.",
  },
  {
    id: "mfg-rheem-ac",
    manufacturer: "Rheem",
    equipmentTypes: ["Air Conditioner"],
    title: "Rheem residential air conditioners product library",
    model: "Current Rheem AC families",
    category: "spec_sheet",
    url: "https://www.rheem.com/products/residential/heating-and-cooling/air_conditioners/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Rheem residential air conditioner product library.",
    verificationNote: "Exact service values require model-specific literature and nameplate confirmation.",
  },
  {
    id: "mfg-rheem-heat-pumps",
    manufacturer: "Rheem",
    equipmentTypes: ["Heat Pump"],
    title: "Rheem residential heat pumps product library",
    model: "Current Rheem heat-pump families",
    category: "spec_sheet",
    url: "https://www.rheem.com/products/residential/heating-and-cooling/heat_pumps/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Rheem residential heat-pump product library.",
    verificationNote: "Use as a source pointer until exact RP/RD family literature and nameplate values are reviewed.",
  },
  {
    id: "mfg-rheem-furnaces",
    manufacturer: "Rheem",
    equipmentTypes: ["Gas Furnace"],
    title: "Rheem residential furnaces product library",
    model: "Current Rheem furnace families",
    category: "spec_sheet",
    url: "https://www.rheem.com/products/residential/heating-and-cooling/furnaces/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Rheem residential furnace library.",
    verificationNote: "Use as a source pointer only until exact model literature is reviewed.",
  },
  {
    id: "mfg-rheem-air-handlers",
    manufacturer: "Rheem",
    equipmentTypes: ["Air Handler"],
    title: "Rheem residential air handlers product library",
    model: "Current Rheem air-handler families",
    category: "spec_sheet",
    url: "https://www.rheem.com/products/residential/heating-and-cooling/air-handlers/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Rheem residential air-handler library.",
    verificationNote: "Use it to locate exact RH-family literature before using electric-heat or airflow values.",
  },
  {
    id: "mfg-ruud-ra14ay",
    manufacturer: "Ruud",
    equipmentTypes: ["Air Conditioner"],
    title: "Ruud Endeavor Line Select Series RA14AY air conditioner",
    model: "RA14AY",
    category: "spec_sheet",
    url: "https://www.ruud.com/product/endeavor-line-select-series-air-conditioner-ra14ay/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Ruud product page for the Endeavor Line Select Series RA14AY air conditioner.",
    verificationNote: "Use as a source pointer until exact submittal and nameplate values are approved.",
  },
  {
    id: "mfg-ruud-ra20az",
    manufacturer: "Ruud",
    equipmentTypes: ["Air Conditioner"],
    title: "Ruud Endeavor Line Prestige Series RA20AZ air conditioner",
    model: "RA20AZ",
    category: "spec_sheet",
    url: "https://www.ruud.com/product/endeavor-line-prestige-series-variable-speed-air-conditioner-ra20az/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Ruud product page for the Endeavor Line Prestige Series RA20AZ variable-speed air conditioner.",
    verificationNote: "Use as a source pointer until exact submittal and nameplate values are approved.",
  },
  {
    id: "mfg-york-ac",
    manufacturer: "York",
    equipmentTypes: ["Air Conditioner", "Package Gas/Electric", "Package Heat Pump", "RTU"],
    title: "York official homeowner product entry",
    model: "Current York families",
    category: "spec_sheet",
    url: "https://www.york.com/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official York brand entry. Deep product URLs were unstable during the research pass.",
    verificationNote: "Use only as a low-confidence source pointer until a current York family PDF or exact model document is approved.",
  },
  {
    id: "mfg-coleman-ac",
    manufacturer: "Coleman",
    equipmentTypes: ["Air Conditioner"],
    title: "Coleman AC official residential entry",
    model: "Current Coleman families",
    category: "spec_sheet",
    url: "https://www.colemanac.com/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Coleman AC brand entry. Deep product URLs were unstable during the research pass.",
    verificationNote: "Use only as a low-confidence source pointer until exact model literature is reviewed.",
  },
  {
    id: "mfg-daikin-ac",
    manufacturer: "Daikin",
    equipmentTypes: ["Air Conditioner"],
    title: "Daikin whole-house air conditioners product library",
    model: "Current Daikin cooling families",
    category: "spec_sheet",
    url: "https://daikincomfort.com/products/heating-cooling/whole-house/air-conditioners",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Daikin whole-house air conditioner library.",
    verificationNote: "Exact values require model-specific literature and nameplate confirmation.",
  },
  {
    id: "mfg-daikin-heat-pumps",
    manufacturer: "Daikin",
    equipmentTypes: ["Heat Pump"],
    title: "Daikin whole-house heat pumps product library",
    model: "Current Daikin heat-pump families",
    category: "spec_sheet",
    url: "https://www.daikincomfort.com/products/heating-cooling/whole-house/heat-pumps",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Daikin whole-house heat-pump product library.",
    verificationNote: "Exact values require model-specific literature and nameplate confirmation.",
  },
  {
    id: "mfg-daikin-ductless",
    manufacturer: "Daikin",
    equipmentTypes: ["Mini-Split Outdoor", "Mini-Split Indoor"],
    title: "Daikin ductless systems product library",
    model: "Current Daikin ductless families",
    category: "service_manual",
    url: "https://www.daikincomfort.com/products/heating-cooling/ductless-systems",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Daikin ductless product library.",
    verificationNote: "Use to locate exact indoor/outdoor model documents before extracting service values.",
  },
  {
    id: "mfg-mitsubishi-products",
    manufacturer: "Mitsubishi Electric",
    equipmentTypes: ["Mini-Split Outdoor", "Mini-Split Indoor", "Heat Pump"],
    title: "Mitsubishi Electric residential products library",
    model: "Current Mitsubishi Electric ductless families",
    category: "service_manual",
    url: "https://www.mitsubishicomfort.com/products",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Mitsubishi Electric product library for ductless and heat-pump equipment.",
    verificationNote: "Use to locate exact indoor/outdoor model documents before extracting service values.",
  },
  {
    id: "mfg-fujitsu-residential",
    manufacturer: "Fujitsu",
    equipmentTypes: ["Mini-Split Outdoor", "Mini-Split Indoor", "Heat Pump"],
    title: "Fujitsu residential products lineup",
    model: "Current Fujitsu residential families",
    category: "service_manual",
    url: "https://www.fujitsugeneral.com/us/residential/index.html",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Fujitsu residential product lineup page.",
    verificationNote: "Use to locate exact model documents before extracting service values.",
  },
  {
    id: "mfg-lg-ductless",
    manufacturer: "LG",
    equipmentTypes: ["Mini-Split Outdoor", "Mini-Split Indoor", "Heat Pump"],
    title: "LG HVAC residential and light commercial library",
    model: "Current LG ductless and inverter families",
    category: "service_manual",
    url: "https://lghvac.com/residential-light-commercial",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official LG HVAC residential and light-commercial product library.",
    verificationNote: "Use it to locate exact indoor or outdoor family material before relying on service guidance.",
  },
  {
    id: "mfg-bosch-heat-pumps",
    manufacturer: "Bosch",
    equipmentTypes: ["Heat Pump", "Air Conditioner"],
    title: "Bosch residential heat pumps product library",
    model: "Current Bosch heat pump families",
    category: "spec_sheet",
    url: "https://www.bosch-homecomfort.com/us/en/ocs/residential/heat-pumps-1098929-c/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bosch Home Comfort residential heat-pump product library.",
    verificationNote: "Use only as a source pointer until exact model literature is reviewed.",
  },
  {
    id: "mfg-bosch-air-handlers",
    manufacturer: "Bosch",
    equipmentTypes: ["Air Handler"],
    title: "Bosch residential air handlers product library",
    model: "Current Bosch air-handler families",
    category: "spec_sheet",
    url: "https://www.bosch-homecomfort.com/us/en/ocs/residential/air-handlers-1098931-c/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Bosch residential air-handler entry.",
    verificationNote: "Use it to find exact BVA or matched air-handler documentation before relying on the values.",
  },
  {
    id: "mfg-amana-heat-pumps",
    manufacturer: "Amana",
    equipmentTypes: ["Heat Pump"],
    title: "Amana heat pumps product library",
    model: "Current Amana heat-pump families",
    category: "spec_sheet",
    url: "https://www.amana-hac.com/products/heat-pumps",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Amana residential heat-pump library.",
    verificationNote: "Use it to locate the exact family PDF, then verify values against the installed model.",
  },
  {
    id: "mfg-amana-gas-furnaces",
    manufacturer: "Amana",
    equipmentTypes: ["Gas Furnace"],
    title: "Amana gas furnaces product library",
    model: "Current Amana gas furnace families",
    category: "spec_sheet",
    url: "https://www.amana-hac.com/products/gas-furnaces",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Amana residential furnace library.",
    verificationNote: "Use as a category pointer until exact model literature is reviewed.",
  },
  {
    id: "mfg-amana-air-handlers-coils",
    manufacturer: "Amana",
    equipmentTypes: ["Air Handler", "Evaporator Coil"],
    title: "Amana air handlers and coils product library",
    model: "Current Amana indoor-unit families",
    category: "spec_sheet",
    url: "https://www.amana-hac.com/products/air-handlers-and-coils",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Amana indoor-unit product library.",
    verificationNote: "Exact matched-system and heat-kit data still require the specific model literature.",
  },
  {
    id: "mfg-honeywell-thermostats",
    manufacturer: "Honeywell",
    equipmentTypes: ["Thermostat"],
    title: "Resideo Honeywell Home thermostats product library",
    model: "Current Honeywell Home thermostats",
    category: "service_manual",
    url: "https://www.resideo.com/us/en/products/air/thermostats/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Resideo/Honeywell Home thermostat product library.",
    verificationNote: "Use to locate the exact thermostat installation guide before changing configuration.",
  },
  {
    id: "mfg-honeywell-zoning",
    manufacturer: "Honeywell",
    equipmentTypes: ["Zoning Panel"],
    title: "Resideo zoning products library",
    model: "Current zoning and panel families",
    category: "service_manual",
    url: "https://www.resideo.com/us/en/pro/products/air/zoning/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Resideo pro zoning library for Honeywell/Resideo zoning panels and accessories.",
    verificationNote: "Open the exact zoning panel or damper control guide before rewiring or changing staging logic.",
  },
  {
    id: "mfg-ecobee-thermostats",
    manufacturer: "Ecobee",
    equipmentTypes: ["Thermostat"],
    title: "ecobee smart thermostats product library",
    model: "Current ecobee thermostats",
    category: "service_manual",
    url: "https://www.ecobee.com/en-us/smart-thermostats/",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official ecobee smart thermostat product library.",
    verificationNote: "Use to locate exact model support material before changing configuration.",
  },
  {
    id: "mfg-nest-thermostats",
    manufacturer: "Nest",
    equipmentTypes: ["Thermostat"],
    title: "Google Nest thermostat product library",
    model: "Current Google Nest thermostat families",
    category: "service_manual",
    url: "https://store.google.com/us/category/nest_thermostats?hl=en-US",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Google Store category page for Nest thermostats.",
    verificationNote: "Use it to identify the installed Nest family, then open the exact support guide before changing wiring or setup.",
  },
  {
    id: "mfg-aprilaire-dehumidifiers",
    manufacturer: "Aprilaire",
    equipmentTypes: ["Dehumidifier"],
    title: "Aprilaire whole-home dehumidifiers product library",
    model: "Current Aprilaire dehumidifier families",
    category: "service_manual",
    url: "https://www.aprilaire.com/whole-house-products/dehumidifier",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Aprilaire dehumidifier category page.",
    verificationNote: "Use it to identify the installed whole-home dehumidifier before opening the exact install or service guide.",
  },
  {
    id: "mfg-aprilaire-humidifiers",
    manufacturer: "Aprilaire",
    equipmentTypes: ["Humidifier"],
    title: "Aprilaire whole-home humidifiers product library",
    model: "Current Aprilaire humidifier families",
    category: "service_manual",
    url: "https://www.aprilaire.com/whole-house-products/humidifier",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Aprilaire humidifier category page.",
    verificationNote: "Use it to identify the installed humidifier before opening the exact install or service guide.",
  },
  {
    id: "mfg-aprilaire-air-purifiers",
    manufacturer: "Aprilaire",
    equipmentTypes: ["Media Air Cleaner", "UV Accessory"],
    title: "Aprilaire air purification product library",
    model: "Current Aprilaire air cleaning families",
    category: "service_manual",
    url: "https://www.aprilaire.com/whole-house-products/air-purifiers",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Aprilaire air-purification category page for media cleaners and UV-style IAQ accessories.",
    verificationNote: "Open the exact air-cleaning or UV accessory guide before changing bulbs, cells, or wiring.",
  },
  {
    id: "mfg-aprilaire-ventilation",
    manufacturer: "Aprilaire",
    equipmentTypes: ["ERV/HRV"],
    title: "Aprilaire ventilation product library",
    model: "Current Aprilaire ventilation families",
    category: "service_manual",
    url: "https://www.aprilaire.com/whole-house-products/ventilation",
    reviewedAt: MANUFACTURER_SOURCE_REVIEWED_AT,
    aiIndexSummary: "Official Aprilaire ventilation category page for fresh-air and ERV/HRV-class accessories.",
    verificationNote: "Use it to identify the installed ventilation accessory before relying on setup or airflow guidance.",
  },
];

function normalize(value?: string) {
  return (value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function typeMatches(source: ManufacturerSourceRecord, equipment: Equipment) {
  const eqType = normalize(equipment.type);
  const eqCategory = normalize(equipment.category);
  return source.equipmentTypes.some((type) => {
    const normalizedType = normalize(type);
    return eqType.includes(normalizedType)
      || normalizedType.includes(eqType)
      || (eqCategory.length > 0 && (eqCategory.includes(normalizedType) || normalizedType.includes(eqCategory)));
  });
}

export function manufacturerDocsForEquipment(equipment: Equipment): ManufacturerSourceRecord[] {
  const manufacturer = normalize(equipment.manufacturer);
  return MANUFACTURER_SOURCE_LIBRARY
    .filter((source) => normalize(source.manufacturer) === manufacturer && typeMatches(source, equipment))
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function manualLinksForEquipment(equipment: Equipment): Equipment["manualUrls"] {
  return manufacturerDocsForEquipment(equipment).map((source) => ({
    label: source.title,
    url: source.url,
  }));
}

export function sourceForManufacturerRecord(record: ManufacturerSourceRecord): Source {
  return {
    kind: "verification_required",
    title: record.title,
    ref: `Reviewed ${record.reviewedAt}; exact model extraction pending`,
    url: record.url,
  };
}

export function manufacturerDocItems(): DocItem[] {
  return MANUFACTURER_SOURCE_LIBRARY.map((source) => ({
    id: source.id,
    title: source.title,
    manufacturer: source.manufacturer,
    model: source.model,
    category: source.category,
    url: source.url,
    status: "Needs Review",
    uploadedAt: source.reviewedAt,
  }));
}
